function encode() {
  const inputText = document.getElementById('input-text').value;
  const outputText = document.getElementById('output-text');

  const mapping = {
                'Y': 'A',
                'X': 'B',
                'B': 'C',
                'Đ': 'D',
                'A': 'E',
                'Z': 'F',
                'C': 'G',
                'G': 'H',
                'E': 'I',
                'F': 'J',
                'H': 'K',
                'K': 'L',
                'L': 'M',
                'M': 'N',
                'I': 'O',
                'N': 'P',
                'P': 'Q',
                'Q': 'R',
                'R': 'S',
                'S': 'T',
                'O': 'U',
                'T': 'V',
                'J': 'W',
                'V': 'X',
                'U': 'Y',
                'W': 'Z',
                //2
                'y': 'a',
                'x': 'b',
                'b': 'c',
                'đ': 'd',
                'a': 'e',
                'z': 'f',
                'c': 'g',
                'g': 'h',
                'e': 'i',
                'f': 'j',
                'h': 'k',
                'k': 'l',
                'l': 'm',
                'm': 'n',
                'i': 'o',
                'n': 'p',
                'p': 'q',
                'q': 'r',
                'r': 's',
                's': 't',
                'o': 'u',
                't': 'v',
                'j': 'w',
                'v': 'x',
                'u': 'y',
                'w': 'z',
